language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
before_deploy:
  - pip install awscli --upgrade --user
deploy:
  provider: script
  script:
    - aws s3 cp dist/ s3://$S3_BUCKET_NAME --recursive --region us-east-1
    - aws s3api put-bucket-website --bucket $S3_BUCKET_NAME --website-configuration file://redirect-rules.json --region us-east-1
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  - echo "deploy is finished"
