language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
deploy:
  provider: script
  script:
    - chmod +x ./aws_configure.sh
    - ./aws_configure.sh
    - npm run deploy
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  - echo "deploy is finished"
